name: Code Coverage Report

on:
  pull_request:
    branches:
      - main

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Run tests and calculate coverage
      - name: Run tests with coverage
        run: |
          npm install
          npm run coverageReport

      - name: Generate code coverage report
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
