name: Jest Coverage Report

on:
  pull_request:
    branches:
      - main

jobs:
  generate-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test -- --coverage --watchAll=false

      - name: Generate coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          files: coverage/lcov-report


      - name: Run tests with coverage
        run: npm run coverageReport

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage

      - name: Calculate Coverage Percentage
        run: node calculate_coverage.js
        id: coverage_percentage

       # Use the coverage percentage output in other steps
      - name: Display coverage
        run: echo Coverage percentage:${{ steps.coverage_percentage.outputs.coverage_percentage}}

      # Determine badge color based on coverage percentage
      - name: Determine badge color
        id: badge_color
        run: |
          coverage_percentage="${{ steps.coverage_percentage.outputs.coverage_percentage }}"
          if [ "$coverage_percentage" -ge 80 ]; then
            color="brightgreen"
          else
            color="red"
          fi
          echo "::set-output name=badge_color::$color"

      # Generate badge URL
      - name: Generate badge URL
        id: badge_url
        run: |
          coverage_percentage="${{ steps.coverage_percentage.outputs.coverage_percentage }}"
          badge_color="${{ steps.badge_color.outputs.badge_color }}"
          badge_url="https://img.shields.io/badge/coverage-$coverage_percentage%25-$badge_color"
          echo "::set-output name=badge_url::$badge_url"

      # Comment on pull request with coverage badge and percentage
      - name: Comment on pull request with coverage badge and percentage
        run: |
          GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          owner="${{ github.repository_owner }}"
          repo="${{ github.event.repository.name }}"
          issue_number="${{ github.event.number }}"
          badge_url="${{ steps.badge_url.outputs.badge_url }}"
          coverage_percentage="${{ steps.coverage_percentage.outputs.coverage_percentage }}"

          run: echo badge_color:${{steps.badge_url.outputs.badge_url}}
          
          body="![Code Coverage]($badge_url)\n\nCoverage: $coverage_percentage%"
          
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\": \"$body\"}" \
            "https://api.github.com/repos/$owner/$repo/issues/$issue_number/comments"


      