name: Jest Coverage Report

on:
  pull_request:
    branches:
      - main

jobs:
  generate-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test -- --coverage --watchAll=false

      - name: Generate coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          files: coverage/lcov-report

      - name: Comment coverage report on PR
        if: always()  # Comment even if previous steps fail
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');
            const reportDir = 'coverage/lcov-report';
            const coverageFiles = fs.readdirSync(reportDir);
            let commentBody = '### Coverage Report\n';
            for (const file of coverageFiles) {
              const filePath = path.join(reportDir, file);
              const fileContent = fs.readFileSync(filePath, 'utf8');
              commentBody += '#### ' + file + '\n';
              commentBody += '```html\n' + fileContent + '\n```\n';
            }
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });