# name: Jest Coverage Comment

# on:
#   pull_request:
#     branches:
#       - main

# jobs:
#   coverage-comment:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       # Run tests and calculate coverage
#       - name: Run tests with coverage
#         run: |
#           npm install
#           npm run coverageReport

#       # Extract coverage percentage
#       - name: Extract coverage percentage
#         id: coverage_percentage
#         run: |
#           coverage=$(cat coverage/coverage-summary.json | jq '.total.lines.pct')
#           echo "::set-output name=coverage_percentage::$coverage"

#       # Determine badge color
#       - name: Determine badge color
#         id: badge_color
#         run: |
#           coverage_percentage="${{ steps.coverage_percentage.outputs.coverage_percentage }}"
#           if [ "$coverage_percentage" -ge 80 ]; then
#             echo "::set-output name=color::brightgreen"
#           else
#             echo "::set-output name=color::red"
#           fi

#       # Generate badge URL
#       - name: Generate badge URL
#         id: badge_url
#         run: |
#           coverage_percentage="${{ steps.coverage_percentage.outputs.coverage_percentage }}"
#           color="${{ steps.badge_color.outputs.color }}"
#           echo "::set-output name=badge_url::https://img.shields.io/badge/coverage-${coverage_percentage}%25-$color"

#       # Comment on PR with coverage
#       - name: Jest Coverage Comment
#         uses: MishaKav/jest-coverage-comment@main
#         with:
#           github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#           coverage-summary-path: coverage/coverage-summary.json
#           comment-title: Jest Coverage
#           status-badge-options: |
#             {
#               "coverageThreshold": 80
#             }
