# Your CI/CD workflow file
name: Update Coverage Badge

on:
  pull_request:
    branches:
      - main

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Run tests and calculate coverage
      - name: Run tests with coverage
        run: |
          npm install
          npm run coverageReport

      # Extract coverage percentage
      - name: Extract coverage percentage
        id: coverage_percentage
        run: |
          # Your script to extract coverage percentage
          coverage=$(cat coverage/coverage-summary.json | jq '.total.lines.pct')
          echo "::set-output name=coverage_percentage::$coverage"

      # Update badge URL in README.md
      - name: Update badge URL
        run: |
          coverage_percentage=$(echo ${{ steps.coverage_percentage.outputs.coverage_percentage }})
          badge_url="https://img.shields.io/badge/coverage-${coverage_percentage}%25-brightgreen"
          sed -i "s|!\[Code Coverage\].*|![Code Coverage]($badge_url)|" README.md
        # Only run when coverage percentage is available
        if: steps.coverage_percentage.outputs.coverage_percentage != ''

      # Commit and push changes
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update code coverage badge
