# name: Jest Coverage Comment

# on:
#   pull_request:
#     branches:
#       - main

# jobs:
#   coverage-comment:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       # Run tests and calculate coverage
#       - name: Run tests with coverage
#         run: |
#           npm install
#           npm run coverageReport

#       # - name: Generate coverage report
#       #   uses: ArtiomTr/jest-coverage-report-action@v2
#       #   with:
#       #     token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#       #     files: coverage/lcov-report

     
#       - name: Jest Coverage Comment
#         uses: MishaKav/jest-coverage-comment@main
#         with:
#           github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#           coverage-summary-path: ./coverage/coverage-summary.json
#           title: Code Coverage 
#           summary-title: Code Coverage summary
#           badge-title: Coverage
#           hide-comment: false
#           create-new-comment: true
#           hide-summary: false
#           junitxml-title: My JUnit Title
#           junitxml-path: ./junit.xml
#           coverage-title: Coverage Report
#           coverage-path: ./coverage.txt
