name: Update Commit Status Check with Coverage Badge

on:
  pull_request:
    branches:
      - main

jobs:
  update-commit-status-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Run tests and calculate coverage
      - name: Run tests with coverage
        run: |
          npm install
          npm run coverageReport

      # Extract coverage percentage
      - name: Extract coverage percentage
        id: coverage_percentage
        run: |
          coverage=$(cat coverage/coverage-summary.json | jq '.total.lines.pct')
          echo "::set-output name=coverage_percentage::$coverage"

     # Update commit status check with badge URL
      - name: Update commit status check with badge URL
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        if: always()  # Update the commit status check even if previous steps fail
        run: |
          coverage_percentage=$(echo 60)
          badge_url="https://img.shields.io/badge/coverage-${coverage_percentage}%25-brightgreen"
          description="![Code Coverage]($badge_url)\n\nCoverage: $coverage_percentage%"
          echo "$description" > coverage_badge.md
          git config user.name 'sumanraj123'
          git config user.email 'sumanravi1124@gmail.com'
          git add coverage_badge.md
          git commit -m "Update code coverage badge"
          git push "https://github.com/sumanraj123/jest_code_coverage.git" HEAD:$GITHUB_REF

        

