name: Code Coverage Report

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm run newCoverage

      - name: Store code coverage report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage

      - name: Extract coverage report URL
        id: extract-url
        run: echo "::set-output name=url::$(echo ${{ github.server_url }}/$(echo ${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/coverage/lcov-report/index.html))"

      - name: Add comment to pull request
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { context, github } = require('@actions/github');
            const { owner, repo, issue: { number } } = context;
            
            const pullRequest = await github.pulls.get({
              owner,
              repo,
              pull_number: number
            });

            const comment = `Code coverage report is available [here](${process.env.url}).`;
            await github.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: comment
            });


