name: Jest Coverage Comment

on:
  pull_request:
    branches:
      - main

jobs:
  coverage-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run coverage

      - name: Generate Jest Coverage Summary
        id: coverageComment
        uses: MishaKav/jest-coverage-comment@main
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          hide-comment: true
          coverage-summary-path: ./coverage/coverage-final.json

      # Extract coverage percentage
      - name: Extract coverage percentage
        id: coverage_percentage
        run: |
          coverage=$(cat coverage/coverage-summary.json | jq '.total.lines.pct')
          echo "::set-output name=coverage_percentage::$coverage"
      
      - name: Check the output coverage
        run: |
          echo "Coverage Percentage - ${{ steps.coverageComment.outputs.coverage }}"
          echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
          echo "Summary HTML - ${{ steps.coverageComment.outputs.summaryHtml }}"


      # Comment on PR with coverage
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          coverage-summary-path: coverage/coverage-summary.json
          comment-title: Jest Coverage
          status-badge-options: |
            {
              "coverageThreshold": 80
            }
          title: My Jest Coverage Comment
          summary-title: My Summary Title
          badge-title: Coverage
          hide-comment: false
          create-new-comment: false
          hide-summary: false
          coverage-title: My Coverage Title
          coverage-path: ./coverage/coverage-final.json
