name: Jest Coverage Comment

on:
  pull_request:
    branches:
      - main

jobs:
  coverage-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Run tests and calculate coverage
      - name: Run tests with coverage
        run: |
          npm install
          npx jest --reporters=default --reporters=jest-junit

      # - name: Generate coverage report
      #   uses: ArtiomTr/jest-coverage-report-action@v2
      #   with:
      #     token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      #     files: coverage/lcov-report

      # # Extract coverage percentage
      # - name: Extract coverage percentage
      #   id: coverage_percentage
      #   run: |
      #     coverage=$(cat coverage/coverage-summary.json | jq '.total.lines.pct')
      #     echo "::set-output name=coverage_percentage::$coverage"

      # Comment on PR with coverage
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-summary-path: coverage/coverage-summary.json
          title: Backend integration Tests
          summary-title: integration Tests
          badge-title: Coverage
          hide-comment: false
          create-new-comment: false
          hide-summary: false
          junitxml-title: My JUnit Title
          junitxml-path: ./junit.xml
          coverage-title: My Coverage Title
          coverage-path: coverage/coverage-summary.json
