name: Jest Coverage Comment

on:
  pull_request:
    branches:
      - main

jobs:
  coverage-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Run tests and calculate coverage
      - name: Run tests with coverage
        run: |
          npm install
          npx jest --coverage | tee ./coverage.txt

      # - name: Generate coverage report
      #   uses: ArtiomTr/jest-coverage-report-action@v2
      #   with:
      #     token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      #     files: coverage/lcov-report

      # # Extract coverage percentage
      # - name: Extract coverage percentage
      #   id: coverage_percentage
      #   run: |
      #     coverage=$(cat coverage/coverage-summary.json | jq '.total.lines.pct')
      #     echo "::set-output name=coverage_percentage::$coverage"

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: ./coverage/coverage-summary.json
          title: My Jest Coverage Comment
          summary-title: My Summary Title
          badge-title: Coverage
          hide-comment: false
          create-new-comment: false
          hide-summary: false
          junitxml-title: My JUnit Title
          junitxml-path: ./junit.xml
          coverage-title: My Coverage Title
          coverage-path: ./coverage.txt
