name: Jest code coverage

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm run coverageReport

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage
          
      - name: Display Coverage Percentage
        id: coverage_percentage
        run: echo Coverage Percentage:${{ steps.coverageReport.outputs.coverage }}

      - name: Set Status Check
        if: ${{ steps.coverage_percentage.outputs.coverage < 80 }}
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.repos.createStatus({
              ...context.repo,
              sha: github.context.payload.pull_request.head.sha,
              state: "failure",
              description: "Code coverage is less than 80%. Please improve code coverage before merging.",
              context: "Code Coverage"
            })

      - name: Finalize Status Check
        if: ${{ steps.coverage_percentage.outputs.coverage >= 80 }}
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.repos.createStatus({
              ...context.repo,
              sha: github.context.payload.pull_request.head.sha,
              state: "success",
              description: "Code coverage is acceptable.",
              context: "Code Coverage"
            })
